<?php

namespace Paymenter\Extensions\Others\ReferralSystem;

use App\Attributes\ExtensionMeta;
use App\Classes\Extension\Extension;
use App\Events\Invoice\Paid as InvoicePaid;
use App\Events\Order\Created as OrderCreated;
use App\Helpers\ExtensionHelper;
use App\Models\Extension as ExtensionModel;
use App\Models\User;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\View;
use Livewire\Livewire;
use Paymenter\Extensions\Others\ReferralSystem\Console\ReferralSystemCommandRegistrar;
use Paymenter\Extensions\Others\ReferralSystem\Listeners\AssociateOrderWithReferral;
use Paymenter\Extensions\Others\ReferralSystem\Listeners\RewardReferralCommission;
use Paymenter\Extensions\Others\ReferralSystem\Livewire\Referrals\Dashboard;
use Paymenter\Extensions\Others\ReferralSystem\Models\ReferralApplication;
use Paymenter\Extensions\Others\ReferralSystem\Models\ReferralCode;
use Paymenter\Extensions\Others\ReferralSystem\Models\ReferralCommission;
use Paymenter\Extensions\Others\ReferralSystem\Models\ReferralManualCommissionSchedule;
use Paymenter\Extensions\Others\ReferralSystem\Models\ReferralWithdrawal;
use Paymenter\Extensions\Others\ReferralSystem\Policies\ReferralApplicationPolicy;
use Paymenter\Extensions\Others\ReferralSystem\Policies\ReferralCodePolicy;
use Paymenter\Extensions\Others\ReferralSystem\Policies\ReferralCommissionPolicy;
use Paymenter\Extensions\Others\ReferralSystem\Policies\ReferralManualCommissionSchedulePolicy;
use Paymenter\Extensions\Others\ReferralSystem\Policies\ReferralWithdrawalPolicy;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralStatsOverview;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralProgramStats;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralRevenueChart;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralActivityChart;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\TopReferrersTable;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralCodePerformance;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralUserAnalyticsStats;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralUserAnalyticsTable;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralUserAnalyticsTrendChart;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralUserDetailResourceTable;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralUserDetailStats;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralUserDetailTrendChart;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralResourceAnalyticsStats;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralResourceAnalyticsTable;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralResourceAnalyticsTrendChart;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralResourceDetailReferrerTable;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralResourceDetailStats;
use Paymenter\Extensions\Others\ReferralSystem\Admin\Widgets\ReferralResourceDetailTrendChart;

#[ExtensionMeta(
    name: 'Referral System',
    description: 'A comprehensive referral and affiliate commission system for Paymenter',
    version: '3.3.0',
    author: 'Cloee',
    icon: 'ri-share-forward-line'
)]

// MADE BY CLOEE
// DO NOT EDIT THIS FILE FOR RESALE OR RE-DISTRIBUTION
// OR I WILL FIND YOU
// CONTACT - CONATCT@CLOEE.PRO
// DISCORD - https://discord.gg/A6TJh5GdVg
// IF SOMEONE SOLD YOU THIS EXTENSION (Other than Cloee) THEN REPORT THEM TO ME
// I WILL NOT BE RESPONSIBLE FOR ANY DAMAGES CAUSED BY EDITING THIS FILE
// THANKS


class ReferralSystem extends Extension
{
    public function __construct(public $config = []) {}

    public function getConfig($values = [])
    {
        return [
            [
                'name' => 'default_revenue_share',
                'label' => 'Default Revenue Share %',
                'type' => 'number',
                'description' => 'Percentage of net invoice revenue awarded to referrers when no product override is defined.',
                'required' => true,
                'default' => 10,
                'suffix' => '%',
                'validation' => 'numeric|min:0|max:100',
            ],
            [
                'name' => 'default_purchase_limit',
                'label' => 'Default Purchase Limit',
                'type' => 'number',
                'description' => 'Maximum number of qualifying purchases per referral code (set 0 for unlimited).',
                'required' => true,
                'default' => 0,
                'validation' => 'integer|min:0',
            ],
            [
                'name' => 'application_requirements',
                'label' => 'Application Requirements Copy',
                'type' => 'textarea',
                'description' => 'Guidelines displayed to customers before they submit a referral application.',
                'required' => false,
                'default' => 'Tell us how you plan to promote Paymenter and the audience you will reach.',
            ],
            [
                'name' => 'allow_custom_code_requests',
                'label' => 'Allow Requested Referral Codes',
                'type' => 'checkbox',
                'description' => 'If enabled, applicants can request a custom referral code string.',
                'default' => true,
            ],
            [
                'name' => 'referral_cookie_days',
                'label' => 'Referral Link Cookie Lifetime',
                'type' => 'number',
                'description' => 'Number of days to keep the referral tracking cookie when a visitor lands on a referral link. Set 0 to disable.',
                'required' => true,
                'default' => 30,
                'validation' => 'integer|min:0',
            ],
            [
                'name' => 'auto_notify_on_approval',
                'label' => 'Email Applicants On Decision',
                'type' => 'checkbox',
                'description' => 'Send an email notification whenever an application is approved or denied.',
                'default' => true,
            ],
            [
                'name' => 'auto_notify_on_purchase',
                'label' => 'Email Referrers On Purchase',
                'type' => 'checkbox',
                'description' => 'Send an email to the referrer whenever a commission is generated.',
                'default' => true,
            ],
            [
                'name' => 'auto_notify_on_withdrawal_update',
                'label' => 'Email Referrers On Withdrawal Updates',
                'type' => 'checkbox',
                'description' => 'Send an email when a withdrawal request is approved or rejected.',
                'default' => true,
            ],
            [
                'name' => 'min_withdrawal_amount',
                'label' => 'Minimum Withdrawal Amount',
                'type' => 'number',
                'description' => 'Minimum amount required to request a withdrawal.',
                'required' => true,
                'default' => 1,
                'validation' => 'numeric|min:1',
            ],
            [
                'name' => 'withdrawal_hold_days',
                'label' => 'Withdrawal Hold Period (Days)',
                'type' => 'number',
                'description' => 'Delay newly earned commissions before they become withdrawable. Set 0 to allow immediate withdrawals.',
                'required' => true,
                'default' => 0,
                'validation' => 'integer|min:0',
            ],
            [
                'name' => 'application_cooldown_days',
                'label' => 'Application Cooldown (Days)',
                'type' => 'number',
                'description' => 'Days a user must wait after a rejection before reapplying (0 = no cooldown).',
                'required' => true,
                'default' => 7,
                'validation' => 'integer|min:0',
            ],
            [
                'name' => 'withdrawal_allowed_currencies',
                'label' => 'Allowed Withdrawal Currencies',
                'type' => 'text',
                'description' => 'Comma-separated ISO currency codes users can withdraw in (example: USD,EUR,GBP). Leave blank to allow any currency with available balance.',
                'required' => false,
                'default' => '',
                'validation' => 'nullable|string|max:255',
            ],
            [
                'name' => 'withdrawal_payment_methods',
                'label' => 'Withdrawal Payment Methods',
                'type' => 'textarea',
                'description' => 'Enter comma or newline separated methods. Use "key:Label" format (example: bank_transfer:Bank Transfer, paypal:PayPal, crypto_wallet:Crypto Wallet).',
                'required' => false,
                'default' => "bank_transfer:Bank Transfer\npaypal:PayPal\ncrypto_wallet:Crypto Wallet",
                'validation' => 'nullable|string|max:2000',
            ],
        ];
    }

    public function enabled(ExtensionModel $extension): void
    {
        // Migrations areh andled in installed() and upgraded()
    }

    public function disabled(ExtensionModel $extension): void
    {
        // Keeping data intact for potential re-enablement
    }

    public function installed(): void
    {
        ExtensionHelper::runMigrations('extensions/Others/ReferralSystem/database/migrations');
    }

    public function uninstalled(): void
    {
        ExtensionHelper::rollbackMigrations('extensions/Others/ReferralSystem/database/migrations');
    }

    public function upgraded($oldVersion = null)
    {
        ExtensionHelper::runMigrations('extensions/Others/ReferralSystem/database/migrations');
    }

    public function boot(): void
    {
        require __DIR__ . '/routes/web.php';

        View::addNamespace('referrals', __DIR__ . '/resources/views');
        Lang::addNamespace('referrals', __DIR__ . '/resources/lang');

        User::resolveRelationUsing('referralApplications', fn (User $user) => $user->hasMany(ReferralApplication::class));
        User::resolveRelationUsing('referralCodes', fn (User $user) => $user->hasMany(ReferralCode::class));

        Livewire::component('referrals.dashboard', Dashboard::class);

        // Register admin widgets with Filament-compatible names (kebab-case from namespace) 548fdcc170237119fce11c345ee45c29
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-stats-overview', ReferralStatsOverview::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-program-stats', ReferralProgramStats::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-revenue-chart', ReferralRevenueChart::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-activity-chart', ReferralActivityChart::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.top-referrers-table', TopReferrersTable::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-code-performance', ReferralCodePerformance::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-user-analytics-stats', ReferralUserAnalyticsStats::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-user-analytics-table', ReferralUserAnalyticsTable::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-user-analytics-trend-chart', ReferralUserAnalyticsTrendChart::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-user-detail-stats', ReferralUserDetailStats::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-user-detail-trend-chart', ReferralUserDetailTrendChart::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-user-detail-resource-table', ReferralUserDetailResourceTable::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-resource-analytics-stats', ReferralResourceAnalyticsStats::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-resource-analytics-trend-chart', ReferralResourceAnalyticsTrendChart::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-resource-analytics-table', ReferralResourceAnalyticsTable::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-resource-detail-stats', ReferralResourceDetailStats::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-resource-detail-trend-chart', ReferralResourceDetailTrendChart::class);
        Livewire::component('paymenter.extensions.others.referral-system.admin.widgets.referral-resource-detail-referrer-table', ReferralResourceDetailReferrerTable::class);

        ReferralSystemCommandRegistrar::register();

        Gate::policy(ReferralApplication::class, ReferralApplicationPolicy::class);
        Gate::policy(ReferralCode::class, ReferralCodePolicy::class);
        Gate::policy(ReferralCommission::class, ReferralCommissionPolicy::class);
        Gate::policy(ReferralManualCommissionSchedule::class, ReferralManualCommissionSchedulePolicy::class);
        Gate::policy(ReferralWithdrawal::class, ReferralWithdrawalPolicy::class);

        ExtensionHelper::registerMiddleware(\Paymenter\Extensions\Others\ReferralSystem\Http\Middleware\TrackReferralCookie::class, 'web');

        Event::listen(OrderCreated::class, AssociateOrderWithReferral::class);
        Event::listen(InvoicePaid::class, RewardReferralCommission::class);

        Event::listen('navigation.account', function () {
            return [
                'name' => __('referrals::referrals.navigation'),
                'route' => 'referrals.dashboard',
            ];
        });

        Event::listen('api.permissions', fn () => $this->permissions());
        Event::listen('permissions', fn () => $this->permissions());

        if (app()->runningInConsole()) {
            $this->registerScheduler();
        }
    }

    private function permissions(): array
    {
        return [
            'admin.referrals.applications.view' => 'View referral applications',
            'admin.referrals.applications.update' => 'Update referral applications',
            'admin.referrals.codes.view' => 'View referral codes',
            'admin.referrals.codes.manage' => 'Manage referral codes',
            'admin.referrals.commissions.view' => 'View referral commissions',
            'admin.referrals.commissions.manage' => 'Manage referral commissions and manual schedules',
            'admin.referrals.withdrawals.manage' => 'Manage referral withdrawals',
            'admin.referrals.analytics.view' => 'View referral analytics pages',
        ];
    }

    protected function registerScheduler(): void
    {
        if (!class_exists(Schedule::class)) {
            return;
        }

        app()->booted(function () {
            /** @var Schedule $schedule */
            $schedule = app(Schedule::class);

            $schedule->command('referrals:manual-commissions:process')
                ->everyFiveMinutes()
                ->withoutOverlapping();
        });
    }
}
